#tomcat
server:
  port: 8080
  servlet:
    context-path: /ly-sys

#spring配置文件
spring:
  application:
    name: ly-sys
  profiles:
    active: dev
  main:
    #同名bean抛异常不覆盖
    allow-bean-definition-overriding: false
    
    