#tomcat
server:
  port: 8081
  servlet:
    context-path: /ly-weixin

#spring配置文件
spring:
  application:
    name: ly-weixin
  profiles:
    active: prod
  main:
    #同名bean抛异常不覆盖
    allow-bean-definition-overriding: false
    
    